In [21]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot

Dataset = load_dataset ('lukebarousse/data_jobs')
df= Dataset['train'].to_pandas()

df ['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [6]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
471704,Data Analyst,"Data Analyst, Payments","Dublin, Ireland",via BeBee Ireland,Full-time,False,Ireland,2023-02-04 15:09:42,True,False,Ireland,NaN,NaN,NaN,AIB Group,NaN,NaN
430197,Data Scientist,Principal Data Scientist,"Irving, TX",via Lensa,Full-time,False,Sudan,2023-06-09 16:39:22,False,False,Sudan,NaN,NaN,NaN,Verizon Media,"['python', 'java', 'r', 'pytorch']","{'libraries': ['pytorch'], 'programming': ['py..."
212629,Data Scientist,Biomedical Data Scientist,"Stanford, CA",via BeBee,Full-time,False,"California, United States",2023-10-22 22:02:36,False,False,United States,NaN,NaN,NaN,Cognoa,"['python', 'sql', 'aws', 'gcp', 'azure', 'tens...","{'cloud': ['aws', 'gcp', 'azure'], 'libraries'..."
113789,Cloud Engineer,Hosting Services Analyst,"Hyderabad, Telangana, India",via Recruit.net,Full-time,False,India,2023-01-27 00:13:36,False,False,India,NaN,NaN,NaN,Epiq,"['sql', 'sas', 'sas', 'c++', 'c#', 'java', 'or...","{'analyst_tools': ['sas', 'nuix', 'ms access']..."
43986,Senior Data Scientist,"Senior Data Scientist, Experimentation Platform","San Francisco, CA",via Indeed,Full-time,False,"California, United States",2023-05-25 06:02:59,False,True,United States,year,203000.0,NaN,Grammarly,"['sql', 'python', 'r', 'scala']","{'programming': ['sql', 'python', 'r', 'scala']}"
200076,Cloud Engineer,Cohesity Technical Engineer,Singapore,via BeBee Singapore,Contractor,False,Singapore,2023-04-11 16:24:47,True,False,Singapore,NaN,NaN,NaN,EXASOFT PTE. LTD.,NaN,NaN
616293,Data Engineer,Data Engineer Internship,"Hoofddorp, Netherlands",via LinkedIn,Internship,False,Netherlands,2023-11-28 12:25:53,False,False,Netherlands,NaN,NaN,NaN,OMRON Healthcare Europe,"['python', 'sql', 'aws']","{'cloud': ['aws'], 'programming': ['python', '..."
769142,Data Analyst,Senior Research and Data Analyst,"Wellington, New Zealand",via LinkedIn,Full-time,False,New Zealand,2023-01-09 01:42:58,True,False,New Zealand,NaN,NaN,NaN,"Ministry of Business, Innovation and Employment","['r', 'css', 'html', 'javascript']","{'programming': ['r', 'css', 'html', 'javascri..."
490532,Senior Data Scientist,福岡 Project Leader- データエンジニア,"Fukuoka, Japan",via LinkedIn,Full-time,False,Japan,2023-09-04 11:29:05,False,False,Japan,NaN,NaN,NaN,Teradata,"['shell', 'sql']","{'programming': ['shell', 'sql']}"
8080,Data Engineer,Principal Data Engineer,"Beaverton, OR",via KHON2 Jobs,Full-time,False,Sudan,2023-01-07 13:26:50,True,False,Sudan,NaN,NaN,NaN,BICP,"['sql', 'python', 'scala', 'java', 'c++', 'aws...","{'cloud': ['aws', 'databricks', 'snowflake'], ..."

In [ ]:
df_test=df.copy
monthly_salary = df.salary_year_avg.median()
df_test['salary_year_avg'] = df_test['salary_year_avg'].fillna(monthly_salary)

In [23]:
df_test['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [24]:
df['salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [26]:
df_test=df
monthly_salary = df.salary_year_avg.median()
df_test['salary_year_avg'] = df_test['salary_year_avg'].fillna(monthly_salary)

In [27]:
df_test['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [28]:
df['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64